### ISSUE TITLE
Core next to each other crash

### ISSUE THREAD

**Issue by tomownu21** [zerofall/EZStorage#16]
when you place 2 cores next to each other they crash the server dunno if you have fixed this yet.

here is the crash log
http://pastebin.com/WVp3TWgf

**Comment by ghost** [comment]
Having the exact same crash, seems the error code to say only one core allowed is using client side only code.  I see this report is 4 days old,please escalate this issue, anything that can bring down a server is major

**Comment by ghost** [comment]
It's important to note that we have one player that now crashes the server every time he logs on, not through malice, the blocks are placed and every time he logs on Bang crash, he is currently waiting to hear on the issue

**Comment by zerofall** [comment]
This is fixed, and there is a new version on CurseForge ready.

**Comment by ghost** [comment]
Timing, lol. I actually removed it from the server and mod pack this am as
we were getting constant crashes on the server.
Wish you all the best though, it's a cool and useful mod.
