### ISSUE TITLE
[1.9] 1.2.0 crashes dedicated forge server 1.9 build 1811

### ISSUE THREAD

**Issue by kreezxil** [zerofall/EZStorage#25]
Issue: ez-storage-1.9-1.2.0 crashes dedicated forge server 1.9 build 1811 when client tries to interact with world

crash report:
https://gist.github.com/0e414f4288ceff36a9f3

fml server latest:
https://gist.github.com/62f73a63d8a6e6530d42

**Comment by VsnGamer** [comment]
Same here, when I break a block it doesnt drop and creates a ghost block then crashes.

**Comment by zerofall** [comment]
Forge updated and changed a few things. It has been fixed.
