### ISSUE TITLE
Original blocks replacing placed blocks

### ISSUE THREAD

**Issue by Ashran14** [zerofall/EZStorage#26]
Minecraft Version: 1.9
Forge Version: 12.16.0.1811
EZ Storage Version: 1.9-1.2.0

When breaking any block in the world and trying to replace it with any other block, (not just the ones from EZ Storage) it gets replaced with the original block that was there. This issue only started after adding EZ Storage to my modlist and stopped occurring as soon as it was removed

**Comment by zerofall** [comment]
Forge updated and changed a few things. It has been fixed.
