### ISSUE TITLE
Shift Clicking item into a full inventory deletes item

### ISSUE THREAD

**Issue by oitsjustjose** [zerofall/EZStorage#4]
Relatively straight forward - when viewing the GUI, if I shift click an item out of the inventory, it disappears; it neither transfers to my inventory, nor falls into the world.

**Comment by zerofall** [comment]
I can't seem to replicate this. Can you give more details? Which version of the mod are you using? In the attached screenshot, when I shift-click the item in the storage core, nothing happens.
![capture](https://cloud.githubusercontent.com/assets/12579976/12919611/92960912-cf0a-11e5-918b-77024efd508a.PNG)

**Comment by Prospector** [comment]
This is just visual. Open up the EZ core and it's there again.

**Comment by oitsjustjose** [comment]
Weird, I can't reproduce the issue anymore.. whelp - sorry to waste your time!
