### ISSUE TITLE
Placing three storage cores next each other crashes

### ISSUE THREAD

**Issue by Watchful1** [zerofall/EZStorage#5]
Which is a totally stupid thing to do, but I somehow managed it.

Here's a crash report: http://pastebin.com/KT9ph9W9

**Comment by zerofall** [comment]
The mod should prevent you from placing multiple cores in 1 multiblock. Is that feature not working for you?

**Comment by Watchful1** [comment]
It works most of the time, but if the server is a bit laggy and you place it quick enough you can get three next to each other.

**Comment by kwpugh** [comment]
I think I'm having the same problem.   I have a user that had multiple cores in the same system, prior to the upgrade.   Now entering his chunk crashes the server.

**Comment by zerofall** [comment]
Watchful1: im going to regard this as user-error. 

kwpugh: That sounds like a different bug, but honestly the mod was never designed to have multiple cores. Im surprised its only crashing on you now. If you really want, open up a new bug and include a log.

**Comment by kwpugh** [comment]
I rolled back to 1.2.2, removed the second core, and rolled forward to 1.2.3.
