### ISSUE TITLE
crash when clicking on jei items to view recipe

### ISSUE THREAD

**Issue by NarigudoBR** [zerofall/EZStorage#9]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  OpenBlocksCorePlugin (OpenBlocks-1.8.9-1.5.0.9.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-30 (1).jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  CorePlugin (Fluxed Redstone-1.1.0.16 (1).jar)
  OpenModsCorePlugin (OpenModsLib-1.8.9-0.9.0.20.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 11/02/16 22:19
Description: Updating screen events

java.lang.NoSuchMethodError: mezz.jei.gui.ingredients.GuiIngredient.getAll()Ljava/util/List;
    at com.zerofall.ezstorage.jei.RecipeTransferHandler.transferRecipe(RecipeTransferHandler.java:45)
    at mezz.jei.transfer.RecipeTransferUtil.transferRecipe(RecipeTransferUtil.java:40)
    at mezz.jei.transfer.RecipeTransferUtil.transferRecipe(RecipeTransferUtil.java:21)
    at mezz.jei.gui.RecipesGui.func_146284_a(RecipesGui.java:319)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:466)
    at mezz.jei.gui.RecipesGui.func_73864_a(RecipesGui.java:247)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
    at mezz.jei.gui.RecipesGui.func_146274_d(RecipesGui.java:223)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.zerofall.ezstorage.jei.RecipeTransferHandler.transferRecipe(RecipeTransferHandler.java:45)
    at mezz.jei.transfer.RecipeTransferUtil.transferRecipe(RecipeTransferUtil.java:40)
    at mezz.jei.transfer.RecipeTransferUtil.transferRecipe(RecipeTransferUtil.java:21)
    at mezz.jei.gui.RecipesGui.func_146284_a(RecipesGui.java:319)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:466)
    at mezz.jei.gui.RecipesGui.func_73864_a(RecipesGui.java:247)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
    at mezz.jei.gui.RecipesGui.func_146274_d(RecipesGui.java:223)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
    Screen name: mezz.jei.gui.RecipesGui

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['samuelvelter2'/3808, l='MpServer', x=-354,83, y=69,00, z=1431,41]]
    Chunk stats: MultiplayerChunkCache: 625, 625
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -67,00,64,00,187,00 - World: (-67,64,187), Chunk: (at 13,4,11 in -5,11; contains blocks -80,0,176 to -65,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 1249737 game time, 1951210 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 96 total; [EntityAuraNode['Aura Node'/3841, l='MpServer', x=-403,50, y=71,50, z=1415,50], EntityCreeper['Creeper'/3842, l='MpServer', x=-376,47, y=16,00, z=1376,03], EntityZombie['Zombie'/3843, l='MpServer', x=-310,50, y=22,00, z=1443,50], EntityZombie['Zombie'/3844, l='MpServer', x=-338,06, y=47,00, z=1473,59], EntitySkeleton['Skeleton'/3845, l='MpServer', x=-394,53, y=28,00, z=1385,88], EntitySkeleton['Skeleton'/3846, l='MpServer', x=-327,50, y=25,00, z=1385,13], EntityCreeper['Creeper'/3848, l='MpServer', x=-312,31, y=37,41, z=1456,81], EntitySpider['Spider'/3849, l='MpServer', x=-319,81, y=39,00, z=1457,16], EntityItem['item.item.arrow'/3850, l='MpServer', x=-330,88, y=67,00, z=1483,81], EntityItem['item.item.bone'/3851, l='MpServer', x=-330,38, y=67,00, z=1484,75], EntityPig['Pig'/3852, l='MpServer', x=-355,19, y=70,00, z=1367,16], EntityCreeper['Creeper'/3853, l='MpServer', x=-303,50, y=25,00, z=1430,50], EntityBat['Bat'/3854, l='MpServer', x=-298,94, y=24,22, z=1431,91], EntityCreeper['Creeper'/3855, l='MpServer', x=-359,03, y=36,00, z=1488,41], EntityBat['Bat'/3856, l='MpServer', x=-358,69, y=66,94, z=1492,72], EntitySkeleton['Skeleton'/3857, l='MpServer', x=-416,31, y=29,00, z=1446,88], EntityChicken['Chicken'/3858, l='MpServer', x=-416,69, y=70,00, z=1416,28], EntityRabbit['Rabbit'/3859, l='MpServer', x=-382,41, y=69,00, z=1368,56], EntityItem['item.item.rottenFlesh'/3860, l='MpServer', x=-292,78, y=13,00, z=1445,13], EntityItem['item.item.rottenFlesh'/3861, l='MpServer', x=-295,88, y=13,00, z=1447,88], EntityZombie['Zombie'/3862, l='MpServer', x=-292,63, y=13,00, z=1445,28], EntityBat['Bat'/3863, l='MpServer', x=-294,91, y=22,94, z=1452,72], EntityCreeper['Creeper'/3864, l='MpServer', x=-303,81, y=22,00, z=1449,19], EntityCreeper['Creeper'/3865, l='MpServer', x=-293,69, y=20,00, z=1447,41], EntityCreeper['Creeper'/3866, l='MpServer', x=-290,91, y=42,00, z=1441,31], EntityZombie['Zombie'/3867, l='MpServer', x=-300,50, y=46,00, z=1443,50], EntityCreeper['Creeper'/3869, l='MpServer', x=-341,50, y=63,00, z=1490,50], EntityChicken['Chicken'/3870, l='MpServer', x=-337,66, y=69,00, z=1492,47], EntitySkeleton['Skeleton'/3871, l='MpServer', x=-412,50, y=29,00, z=1478,50], EntityZombie['Zombie'/3872, l='MpServer', x=-408,50, y=25,00, z=1477,50], EntitySkeleton['Skeleton'/3873, l='MpServer', x=-316,50, y=19,00, z=1473,50], EntityBat['Bat'/3874, l='MpServer', x=-421,25, y=58,91, z=1456,53], EntityZombie['Zombie'/3875, l='MpServer', x=-385,97, y=31,00, z=1357,50], EntityAuraNode['Aura Node'/3876, l='MpServer', x=-395,50, y=73,50, z=1373,50], EntityEnderman['Enderman'/3878, l='MpServer', x=-400,47, y=71,00, z=1369,91], EntityCreeper['Creeper'/3881, l='MpServer', x=-362,72, y=64,53, z=1353,47], EntitySheep['Sheep'/3882, l='MpServer', x=-309,16, y=68,00, z=1368,03], EntitySheep['Sheep'/3883, l='MpServer', x=-294,69, y=67,00, z=1384,41], EntitySheep['Sheep'/3884, l='MpServer', x=-303,69, y=68,00, z=1379,41], EntitySpider['Spider'/3886, l='MpServer', x=-297,50, y=23,00, z=1475,50], EntityBat['Bat'/3887, l='MpServer', x=-290,91, y=31,00, z=1479,25], EntitySheep['Sheep'/3891, l='MpServer', x=-373,72, y=72,00, z=1356,63], EntityPig['Pig'/3892, l='MpServer', x=-369,31, y=71,00, z=1355,47], EntityAuraNode['Aura Node'/3893, l='MpServer', x=-346,50, y=32,50, z=1355,50], EntitySkeleton['Skeleton'/3894, l='MpServer', x=-287,50, y=28,00, z=1418,88], EntityMinecartChest['container.minecart'/3902, l='MpServer', x=-385,50, y=35,00, z=1353,50], EntitySkeleton['Skeleton'/3905, l='MpServer', x=-275,50, y=49,00, z=1404,50], EntityZombie['Zombie'/3906, l='MpServer', x=-280,50, y=49,00, z=1406,50], EntitySheep['Sheep'/3907, l='MpServer', x=-280,34, y=66,00, z=1404,22], EntityZombie['Zombie'/3910, l='MpServer', x=-419,91, y=31,00, z=1369,31], EntityCreeper['Creeper'/3911, l='MpServer', x=-428,50, y=63,00, z=1360,50], EntityRabbit['Rabbit'/3912, l='MpServer', x=-302,50, y=67,00, z=1365,88], EntityRabbit['Rabbit'/3913, l='MpServer', x=-299,41, y=67,00, z=1371,13], EntityAuraNode['Aura Node'/3914, l='MpServer', x=-295,50, y=89,50, z=1363,50], EntityPig['Pig'/3915, l='MpServer', x=-296,50, y=69,00, z=1493,28], EntityZombie['Zombie'/3918, l='MpServer', x=-279,50, y=48,00, z=1383,91], EntityCow['Cow'/3919, l='MpServer', x=-279,44, y=65,00, z=1379,66], EntityBat['Bat'/3920, l='MpServer', x=-311,16, y=59,66, z=1506,22], EntityAuraNode['Aura Node'/3933, l='MpServer', x=-390,50, y=63,50, z=1535,50], EntityBat['Bat'/3945, l='MpServer', x=-280,47, y=50,47, z=1368,50], EntityZombie['Zombie'/3946, l='MpServer', x=-279,81, y=50,00, z=1365,75], EntitySkeleton['Skeleton'/3947, l='MpServer', x=-275,50, y=24,00, z=1499,50], EntitySkeleton['Skeleton'/3948, l='MpServer', x=-277,50, y=52,00, z=1502,50], EntityZombie['Zombie'/3961, l='MpServer', x=-286,50, y=19,00, z=1352,50], EntityPig['Pig'/3970, l='MpServer', x=-286,47, y=65,00, z=1507,88], EntityItem['item.item.egg'/4740, l='MpServer', x=-399,41, y=68,00, z=1457,25], EntityAuraNode['Aura Node'/3974, l='MpServer', x=-256,50, y=67,50, z=1369,50], EntityAuraNode['Aura Node'/4055, l='MpServer', x=-498,50, y=90,50, z=1369,50], EntityPlayerSP['samuelvelter2'/3808, l='MpServer', x=-354,83, y=69,00, z=1431,41], EntityBat['Bat'/3810, l='MpServer', x=-357,75, y=47,10, z=1447,25], EntityCreeper['Creeper'/3811, l='MpServer', x=-355,31, y=45,53, z=1452,47], EntityCreeper['Creeper'/3812, l='MpServer', x=-362,03, y=45,41, z=1443,56], EntityBat['Bat'/3813, l='MpServer', x=-353,59, y=46,10, z=1447,72], EntityCreeper['Creeper'/3814, l='MpServer', x=-379,00, y=56,00, z=1451,13], EntityZombie['Zombie'/3815, l='MpServer', x=-381,28, y=56,00, z=1449,84], EntityBat['Bat'/3816, l='MpServer', x=-375,25, y=59,10, z=1416,25], EntitySkeleton['Skeleton'/3817, l='MpServer', x=-374,63, y=57,00, z=1418,06], EntitySkeleton['Skeleton'/3818, l='MpServer', x=-338,31, y=40,00, z=1451,66], EntityCreeper['Creeper'/3819, l='MpServer', x=-338,84, y=40,00, z=1453,16], EntitySkeleton['Skeleton'/3820, l='MpServer', x=-353,25, y=31,00, z=1405,69], EntityItem['item.item.ItemSquid'/3821, l='MpServer', x=-373,56, y=60,00, z=1468,94], EntityItem['item.item.ItemSquid'/3822, l='MpServer', x=-374,91, y=60,00, z=1470,22], EntityItem['item.item.dyePowder.black'/3823, l='MpServer', x=-374,63, y=60,00, z=1469,25], EntitySpider['Spider'/3824, l='MpServer', x=-383,50, y=60,00, z=1471,50], EntityZombie['Zombie'/3825, l='MpServer', x=-371,31, y=58,00, z=1458,50], EntitySquid['Squid'/3826, l='MpServer', x=-377,53, y=61,00, z=1469,41], EntityZombie['Zombie'/3827, l='MpServer', x=-391,53, y=59,00, z=1449,06], EntityItem['item.tile.stonebrick'/3828, l='MpServer', x=-326,91, y=69,00, z=1443,13], EntityItem['item.tile.stonebrick'/3829, l='MpServer', x=-328,78, y=70,00, z=1442,31], EntityItem['item.tile.stonebrick'/3830, l='MpServer', x=-328,38, y=70,00, z=1441,44], EntityItem['item.tile.stonebrick'/3831, l='MpServer', x=-326,56, y=70,00, z=1442,44], EntityItem['item.tile.stonebrick'/3832, l='MpServer', x=-327,13, y=68,00, z=1443,44], EntityItem['item.tile.stonebrick'/3833, l='MpServer', x=-326,44, y=69,00, z=1446,50], EntityItem['item.tile.stonebrick'/3834, l='MpServer', x=-327,88, y=68,00, z=1443,84], EntityChicken['Chicken'/3835, l='MpServer', x=-398,47, y=68,00, z=1456,59], EntityRabbit['Rabbit'/3836, l='MpServer', x=-387,72, y=69,00, z=1400,56]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    CPU: 2x Intel(R) Pentium(R) CPU G620 @ 2.60GHz
    Java Version: 1.8.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 209860096 bytes (200 MB) / 1301807104 bytes (1241 MB) up to 3176660992 bytes (3029 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1732 Optifine OptiFine_1.8.9_HD_U_H2 56 mods loaded, 56 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1732.jar) 
    UCHIJAAAA   Forge{11.15.1.1732} [Minecraft Forge](forge-1.8.9-11.15.1.1732.jar) 
    UCHIJAAAA   OpenModsCore{0.9.0.20} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   basemetals{1.6.2} [Base Metals](BaseMetals-1.6.2.jar) 
    UCHIJAAAA   bookshelfapi{2.3.0} [Bookshelf](Bookshelf-1.8.9-2.3.0.jar) 
    UCHIJAAAA   BuildCraft|Core{7.2.0-pre10} [BuildCraft](buildcraft-7.2.0-pre10.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.2.0-pre10} [BC Energy](buildcraft-7.2.0-pre10.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.2.0-pre10} [BC Transport](buildcraft-7.2.0-pre10.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.2.0-pre10} [BC Robotics](buildcraft-7.2.0-pre10.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.2.0-pre10} [BC Builders](buildcraft-7.2.0-pre10.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.2.0-pre10} [BC Factory](buildcraft-7.2.0-pre10.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.2.0-pre10} [BC Silicon](buildcraft-7.2.0-pre10.jar) 
    UCHIJAAAA   Chameleon{1.8.9-0.2.1} [Chameleon](Chameleon-1.8.9-0.2.1.jar) 
    UCHIJAAAA   mcmultipart{1.0.6} [MCMultiPart](MCMultiPart-1.0.6-universal.jar) 
    UCHIJAAAA   chiselsandbits{mc1.8.9-v1.8.9} [Chisels & Bits](chiselsandbits-mc1.8.9-v1.8.9.jar) 
    UCHIJAAAA   poweradvantage{1.4.4} [Power Advantage](PowerAdvantage-1.4.4.jar) 
    UCHIJAAAA   electricadvantage{1.0.5} [Electric Advantage](ElectricAdvantage-1.1.0.jar) 
    UCHIJAAAA   ShetiPhianCore{3.1.0} [ShetiPhian-Core](ShetiPhianCore-1.8.9-3.1.0.jar) 
    UCHIJAAAA   EnderTanks{1.2.1} [EnderTanks](EnderTanks-1.8.9-1.2.1.jar) 
    UCHIJAAAA   ezstorage{1.0} [EZ Storage](ezstorage-1.8.9-1.2.2.jar) 
    UCHIJAAAA   reborncore{1.4.0.13} [RebornCore](RebornCore-1.8.9-1.4.0.13-universal %281%29.jar) 
    UCHIJAAAA   fluxedredstone{1.1.0.16} [FluxedRedstone](Fluxed Redstone-1.1.0.16 %281%29.jar) 
    UCHIJAAAA   fluxedcore{2.0.2} [Fluxed-Core](Fluxed-Core-1.8.9-2.0.2.jar) 
    UCHIJAAAA   fluxedsolars{$GRADLEVERSION} [Fluxed Solars](fluxedsolars-1.9.jar) 
    UCHIJAAAA   fe{1.1} [Food Expansion](FoodExpansion1.1-mc1.8.9.jar) 
    UCHIJAAAA   furnus{1.7} [Furnus](Furnus-1.8.9-1.7.jar) 
    UCHIJAAAA   graves{1.8.9-b36-universal} [Graves Mod](graves-1.8.9-b36-universal.jar) 
    UCHIJAAAA   IGWMod{1.2.3-3} [In-Game wiki Mod](IGW-Mod-1.8.9-1.2.3-3-universal.jar) 
    UCHIJAAAA   inventorysorter{0.7.4+26} [Simple Inventory sorting](inventorysorter-1.8.9-0.7.4+26.jar) 
    UCHIJAAAA   inventorytweaks{1.60-beta-30-48a432c} [Inventory Tweaks](InventoryTweaks-1.60-beta-30 %281%29.jar) 
    UCHIJAAAA   ironbackpacks{1.8.9-2.0.5} [Iron Backpacks](IronBackpacks-1.8.9-2.0.5.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest](ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   JEI{2.25.6.140} [Just Enough Items](jei_1.8.9-2.25.6.140.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   Thaumcraft{5.1.6} [Thaumcraft](Thaumcraft-1.8.9-5.1.6.jar) 
    UCHIJAAAA   JEIAddons{0.11.2.56} [Just Enough Items Addons](JEIAddons_1.8.9-0.11.2.56.jar) 
    UCHIJAAAA   journeymap{5.1.3} [JourneyMap](journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJAAAA   llor{1.0.4-mc1.8.8} [Light Level Overlay Reloaded](LLOverlayReloaded-1.0.4-mc1.8.8.jar) 
    UCHIJAAAA   mantle{1.8.9-0.7.jenkins72} [Mantle](Mantle-1.8.9-0.7.jar) 
    UCHIJAAAA   neotech{2.3.5} [NeoTech](NeoTech-1.8.9-2.3.5.jar) 
    UCHIJAAAA   OpenMods{0.9.0.20} [OpenMods](OpenModsLib-1.8.9-0.9.0.20.jar) 
    UCHIJAAAA   OpenBlocks{1.5.0.9} [OpenBlocks](OpenBlocks-1.8.9-1.5.0.9.jar) 
    UCHIJAAAA   getalltheseeds{1.8.9a} [Pam's Get all the Seeds!](Pam's Get all the Seeds! 1.8.9a.jar) 
    UCHIJAAAA   parachutemod{1.2.0} [Parachute Mod](parachutemod-ng-1.8.9-1.2.0-321.jar) 
    UCHIJAAAA   PneumaticCraft{1.13.6} [PneumaticCraft](PneumaticCraft-1.8.9-1.13.6-universal.jar) 
    UCHIJAAAA   progressiveautomation{1.6.33} [Progressive Automation](ProgressiveAutomation-1.8.9-1.6.33.jar) 
    UCHIJAAAA   mrdimkaraytracelib{0.0.1} [MrDimka's Ray Trace Library](RayTraceLib_1.8.9-0.0.1.jar) 
    UCHIJAAAA   SilentGems{1.3.9b} [Silent's Gems](SilentsGems-1.8.9-1.3.9b-102.jar) 
    UCHIJAAAA   simpleretrogen{2.2.2+3} [Simple Retrogen](simpleretrogen-1.8.9-2.2.2+3.jar) 
    UCHIJAAAA   steamadvantage{1.5.1} [Steam Advantage](SteamAdvantage-1.5.1.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.3.4} [Storage Drawers](StorageDrawers-1.8.9-2.3.4.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct](TConstruct-1.8.9-2.0.2.jar) 
    UCHIJAAAA   thaumicadditions{0.39} [Thaumic Additions](Thaumic Additions - 1.8.9 - 0.39.jar) 
    UCHIJAAAA   ToolsOnTheGo{1.8.9} [Tools on the Go](ToolsOnTheGo-1.8.9.1.2.1.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
    Loaded coremods (and transformers): 
OpenBlocksCorePlugin (OpenBlocks-1.8.9-1.5.0.9.jar)
  openblocks.asm.OpenBlocksClassTransformer
FMLPlugin (InventoryTweaks-1.60-beta-30 (1).jar)
  invtweaks.forge.asm.ContainerTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)

CorePlugin (Fluxed Redstone-1.1.0.16 (1).jar)

OpenModsCorePlugin (OpenModsLib-1.8.9-0.9.0.20.jar)
  openmods.core.OpenModsClassTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 359.06' Renderer: 'GeForce GT 545/PCIe/SSE2'
    OpenModsLib class transformers: [movement_callback:FINISHED],[map_gen_fix:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - TinkerDebug (Enabled/Not Forced)

```
Launched Version: 1.8.9-forge1.8.9-11.15.1.1732
LWJGL: 2.9.4
OpenGL: GeForce GT 545/PCIe/SSE2 GL version 4.5.0 NVIDIA 359.06, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 2x Intel(R) Pentium(R) CPU G620 @ 2.60GHz
```

**Comment by zerofall** [comment]
This was already fixed in the latest version: 1.2.3
